version: '3.8'

volumes:
  yarn-cache:

services:
  web:
    container_name: hic_web
    image: nginx:1-alpine
    depends_on:
      - app
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  web-dev:
    container_name: hic_web-dev
    build:
      context: .
      dockerfile: Dockerfile_nginx-dev
    depends_on:
      - app-dev
    ports:
      - 8080:8080

  db:
    container_name: hic_db
    image: mongo:4-bionic
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mongopw

  app:
    container_name: hic_app
    build:
      context: .
      dockerfile: Dockerfile_app
    volumes:
      - yarn-cache:/yarn-cache
      - .:/project
    working_dir: /project
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    depends_on:
      - db
    ports:
      - 3000:3000
    command: pm2-runtime start docker-pm2.config.json

  app-dev:
    container_name: hic_app-dev
    build:
      context: .
      dockerfile: Dockerfile_app-dev
    volumes:
      - yarn-cache:/yarn-cache
      - .:/project
    working_dir: /project
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
      - 35729:35729
    depends_on:
      - db
    command: pm2-runtime --formatted start docker-pm2-dev.config.js

  node:
    image: simbo/node:14
    volumes:
      - yarn-cache:/yarn-cache
      - .:/project
    working_dir: /project
    tty: true
    stdin_open: true
    command: bash
